[package]
name = "wall-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
rand = "0.8.5"
wallpaper = "3.2.0"
